import typography from '@tailwindcss/typography';
import type { Config } from 'tailwindcss';

export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    darkMode: 'selector',
    theme: {
        extend: {
            colors: {
                'page-bg': 'var(--color-page-bg)',
                'page-bg-dark': 'var(--color-page-bg-dark)',
                'page-bg-muted': 'var(--color-page-bg-muted)',
                'page-bg-muted-dark': 'var(--color-page-bg-muted-dark)',

                surface: 'var(--color-surface)',
                'surface-dark': 'var(--color-surface-dark)',
                'surface-hover': 'var(--color-surface-hover)',
                'surface-hover-dark': 'var(--color-surface-hover-dark)',
                'surface-code': 'var(--color-surface-code)',
                'surface-code-dark': 'var(--color-surface-code-dark)',

                'border-default': 'var(--color-border-default)',
                'border-default-dark': 'var(--color-border-default-dark)',
                'border-medium': 'var(--color-border-medium)',
                'border-medium-dark': 'var(--color-border-medium-dark)',
                'border-subtle': 'var(--color-border-subtle)',
                'border-subtle-dark': 'var(--color-border-subtle-dark)',

                'text-primary': 'var(--color-text-primary)',
                'text-primary-dark': 'var(--color-text-primary-dark)',
                'text-secondary': 'var(--color-text-secondary)',
                'text-secondary-dark': 'var(--color-text-secondary-dark)',
                'text-muted': 'var(--color-text-muted)',
                'text-muted-dark': 'var(--color-text-muted-dark)',

                link: 'var(--color-link)',
                'link-hover': 'var(--color-link-hover)',
                'link-dark': 'var(--color-link-dark)',
                'link-hover-dark': 'var(--color-link-hover-dark)',
                'link-active': 'var(--color-link-active)',
                'link-active-dark': 'var(--color-link-active-dark)',

                'button-primary-bg': 'var(--color-button-primary-bg)',
                'button-primary-bg-dark': 'var(--color-button-primary-bg-dark)',
                'button-primary-bg-hover': 'var(--color-button-primary-bg-hover)',
                'button-primary-bg-hover-dark': 'var(--color-button-primary-bg-hover-dark)',
                'button-primary-text': 'var(--color-button-primary-text)',
                'button-primary-text-dark': 'var(--color-button-primary-text-dark)',
                'button-primary-text-hover': 'var(--color-button-primary-text-hover)',
                'button-primary-text-hover-dark': 'var(--color-button-primary-text-hover-dark)',

                'button-secondary-bg': 'var(--color-button-secondary-bg)',
                'button-secondary-bg-dark': 'var(--color-button-secondary-bg-dark)',
                'button-secondary-bg-hover': 'var(--color-button-secondary-bg-hover)',
                'button-secondary-bg-hover-dark': 'var(--color-button-secondary-bg-hover-dark)',
                'button-secondary-text': 'var(--color-button-secondary-text)',
                'button-secondary-text-dark': 'var(--color-button-secondary-text-dark)',
                'button-secondary-text-hover': 'var(--color-button-secondary-text-hover)',
                'button-secondary-text-hover-dark': 'var(--color-button-secondary-text-hover-dark)',

                'button-outline-bg': 'var(--color-button-outline-bg)',
                'button-outline-bg-dark': 'var(--color-button-outline-bg-dark)',
                'button-outline-bg-hover': 'var(--color-button-outline-bg-hover)',
                'button-outline-bg-hover-dark': 'var(--color-button-outline-bg-hover-dark)',
                'button-outline-border': 'var(--color-button-outline-border)',
                'button-outline-border-dark': 'var(--color-button-outline-border-dark)',
                'button-outline-border-hover': 'var(--color-button-outline-border-hover)',
                'button-outline-border-hover-dark': 'var(--color-button-outline-border-hover-dark)',
                'button-outline-text': 'var(--color-button-outline-text)',
                'button-outline-text-dark': 'var(--color-button-outline-text-dark)',
                'button-outline-text-hover': 'var(--color-button-outline-text-hover)',
                'button-outline-text-hover-dark': 'var(--color-button-outline-text-hover-dark)',

                'focus-ring': 'var(--color-focus-ring)',
                'focus-ring-dark': 'var(--color-focus-ring-dark)',

                'info-bg': 'var(--color-info-bg)',
                'info-bg-dark': 'var(--color-info-bg-dark)',
                'info-border': 'var(--color-info-border)',
                'warning-bg': 'var(--color-warning-bg)',
                'warning-bg-dark': 'var(--color-warning-bg-dark)',
                'warning-border': 'var(--color-warning-border)',
                'warning-border-dark': 'var(--color-warning-border-dark)',
                'warning-text': 'var(--color-warning-text)',
                'warning-text-dark': 'var(--color-warning-text-dark)',
                'warning-heading': 'var(--color-warning-heading)',
                'warning-heading-dark': 'var(--color-warning-heading-dark)',
                'warning-highlight': 'var(--color-warning-highlight)',
                'warning-highlight-dark': 'var(--color-warning-highlight-dark)',
                'success-text': 'var(--color-success-text)',
                'success-text-dark': 'var(--color-success-text-dark)',
                'error-text': 'var(--color-error-text)',
                'error-text-dark': 'var(--color-error-text-dark)',

                'tag-bg': 'var(--color-tag-bg)',
                'tag-bg-dark': 'var(--color-tag-bg-dark)',
                'tag-text': 'var(--color-tag-text)',
                'tag-text-dark': 'var(--color-tag-text-dark)',
            },
        },
    },
    plugins: [typography],
} satisfies Config;
